---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-flavor
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: nova-flavor
    app.kubernetes.io/instance: {{ .Release.Name }}
